### ISSUE TITLE
List of new features

### ISSUE THREAD

**Issue by pikersky** [migotom/mt-bulk#1]
- bulk firmware/software update
- bulk backup
- GUI
- bulk MT scan for backdoor vulnerabilities
...

**Comment by migotom** [comment]
Please open one issue per requested feature and describe each of them (this will allow easy track progress and discussion of each feature).

**Comment by pikersky** [comment]
01110011 01110011 01101001 01101010 00100000 01101010 01100001 01101010 01100011 01100001

**Comment by pikersky** [comment]
73 73 69 6A 2 ,6A 61 6A 63 61
