### ISSUE TITLE
Try next IP on "can't resolve host x.x.x.x"

### ISSUE THREAD

**Issue by Gareth-CMVAS** [migotom/mt-bulk#13]
**Is your feature request related to a problem? Please describe.**
I would like to backup a mass amount of devices of which have dynamic ip's, I have a hosts.txt with all possibilities (/16 subnet), however MT-Bulk stops the script when the host is unreachable instead of trying the next.

**Describe the solution you'd like**
Provide an IP range, which will try to SSH and do a system backup skipping down hsots.

**Describe alternatives you've considered**
I have run manual pings to find devices that are up in the mean time and provided a list.

**Comment by migotom** [comment]
Fixed by release v2.3.0
