### ISSUE TITLE
Problem z upgrade

### ISSUE THREAD

**Issue by carnivean14** [migotom/mt-bulk#6]
**Describe the bug**
Brak wyświetlenia rezultatu komendy print w system->upgrade po wykonaniu polecenia refresh. Polecenie /user print zostało do sprawdzenia czy w ogóle coś wyświetla.

Config:

# commands to run with SSH
[[custom-ssh.command]]
body = "/user print; /system upgrade refresh; /system upgrade print;"

W lini poleceń MT:

![screenshot_4](https://user-images.githubusercontent.com/48247998/53942405-f4ffa480-40ba-11e9-8ad6-f383fb916d40.png)

Wynik z programu:

![screenshot_3](https://user-images.githubusercontent.com/48247998/53941841-76eece00-40b9-11e9-8149-627d5edc7e45.png)

Soft mt: 6.40.4, 6.44

**Comment by pikersky** [comment]
To jakiś bug w rOS. Wpisz bezpośrednio na MT "**/system upgrade refresh; /system upgrade print;**" (w ciągu nie komenda po komendzie)  zobacz, że również zwraca puste.

**Comment by migotom** [comment]
w takim razie proponuje sprawdzic:
```
[[custom-ssh.command]]
body = "/user print"
[[custom-ssh.command]]
body = "/system upgrade refresh"
[[custom-ssh.command]]
body = "/system upgrade print"
```

Mozna dodac atrybut expected jesli spodziewamy sie jakiegos konkretnego wyniku komendy.

**Comment by carnivean14** [comment]
![screenshot_2](https://user-images.githubusercontent.com/48247998/53954812-8f6de100-40d7-11e9-88cd-105747543b52.png)

dalej pusto

**Comment by pikersky** [comment]
Takie rozwiązanie na szybko `/system upgrade refresh ;delay 1 ;  /system upgrade print`

**Comment by migotom** [comment]
Fixed with commit d62486aca7a7f6f6233d69441ef62c9f10d583b4

**Comment by migotom** [comment]
Działający config na wersji v1.3

```
[[custom-ssh.command]]
body = "/user print"
[[custom-ssh.command]]
body = "/system upgrade refresh"
sleep = "1s"
[[custom-ssh.command]]
body = "/system upgrade print"
```

**Comment by carnivean14** [comment]
Działa. 
Dobra robota.
